change order..12

diff --git a/.github/workflows/project.yml b/.github/workflows/project.yml
--- a/.github/workflows/project.yml
+++ b/.github/workflows/project.yml
@@ -86,29 +86,75 @@ jobs:
       run: |
               RDS_ENDPOINT=$(aws rds describe-db-instances --query "DBInstances[0].Endpoint.Address" --output text)
               echo "DB_HOST=$RDS_ENDPOINT" >> $GITHUB_ENV
-          
+      
+    - name: Check Database Connection and Stop Migrator
+      if: success() # This step only runs if all previous steps were successful
+      run: |
+         connected=false
+         while [ $connected != true ]; do
+         psql -h ${{ env.DB_HOST }} -U ${{ secrets.DBUSERNAME }} -d ${{ secrets.DATABASE }} -c "SELECT 1"
+         if [ $? -eq 0 ]; then
+           echo "Database connection successful."
+           connected=true
+         else
+           echo "Database connection failed. Migrator task will continue."
         
-    - name: Check Database Connection and Keep Migrator Running
-      id: check-connection
-      run: |
-                connected=false
-                while [ $connected != true ]; do
-                  psql -h ${{ env.DB_HOST }} -U ${{ secrets.DB_USERNAME }} -d ${{ secrets.DB_DATABASE }} -c "SELECT 1"
-                  if [ $? -eq 0 ]; then
-                    echo "Database connection successful."
-                    connected=true
-                  else
-                    echo "Database connection failed. Migrator task will continue."
-                    # Wait for a brief period before trying again (adjust as needed)
-                    sleep 10
-                  fi
-                done
+           sleep 10
+         fi 
+         done
+
+         if [ $connected = true ]; then
+           echo "Stopping migrator task..."
+           aws ecs stop-task --cluster your-cluster-name --task ${{ steps.start-migrator.outputs.task_arn }}
+         fi
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+        
+    # - name: Check Database Connection and Keep Migrator Running
+    #   id: check-connection
+    #   run: |
+    #             connected=false
+    #             while [ $connected != true ]; do
+    #               psql -h ${{ env.DB_HOST }} -U ${{ secrets.DB_USERNAME }} -d ${{ secrets.DB_DATABASE }} -c "SELECT 1"
+    #               if [ $? -eq 0 ]; then
+    #                 echo "Database connection successful."
+    #                 connected=true
+    #               else
+    #                 echo "Database connection failed. Migrator task will continue."
+    #                 # Wait for a brief period before trying again (adjust as needed)
+    #                 sleep 10
+    #               fi
+    #             done
             
-    - name: Stop Migrator Task
-      if: steps.check-connection.outputs.connected == 'true'
-      run: |
-                echo "Stopping migrator task..."
-                aws ecs stop-task --cluster your-cluster-name --task ${{ steps.migrator-task.outputs.task_arn }}
+    # - name: Stop Migrator Task
+    #   if: steps.check-connection.outputs.connected == 'true'
+    #   run: |
+    #             echo "Stopping migrator task..."
+    #             aws ecs stop-task --cluster your-cluster-name --task ${{ steps.migrator-task.outputs.task_arn }}
         
     - name: Update other services
       run: |
